"""Simulation runner.

SimulationRunner wires together:
  - a RoadNetwork
  - a list of ChargingStation objects (with SimPy Resources created here)
  - a list of TripRequest objects (converted to VehicleAgent instances)
  - a SimPy environment

and runs the discrete-event simulation, returning a SimulationResults object.

Agent creation
--------------
Each TripRequest is converted to a VehicleAgent with heterogeneous
behavioral parameters sampled from distributions defined in
data_generation/synthetic.py (or overridden via the config).

Calibration hooks
-----------------
``run()`` accepts an optional ``od_flow_observer`` callback that receives
(link_id, agent_id, sim_time_min) at each edge traversal.  This is the
interface through which a calibrator can compare simulated link counts
to observed IMD data.
"""

from __future__ import annotations

import logging
from typing import Callable, Dict, List, Optional

import numpy as np
import simpy

from models.agent import VehicleAgent
from models.demand import TripRequest
from models.network import RoadNetwork
from models.results import ResultsCollector, SimulationResults
from models.station import ChargingStation
from simulation.engine import vehicle_trip_process

logger = logging.getLogger(__name__)


class SimulationRunner:
    """
    Orchestrates the full discrete-event simulation.

    Usage
    -----
    >>> runner = SimulationRunner(network, stations, config)
    >>> results = runner.run(trip_requests, scenario_name="baseline")
    >>> print(results.summary_dict())
    """

    def __init__(
        self,
        network: RoadNetwork,
        stations: List[ChargingStation],
        config: Dict,
    ) -> None:
        self.network = network
        self.stations = stations
        self.config = config

        # Build node → station mapping for fast lookup
        self.stations_by_node: Dict[str, List[ChargingStation]] = {}
        for s in stations:
            self.stations_by_node.setdefault(s.node_id, []).append(s)

    def run(
        self,
        trip_requests: List[TripRequest],
        scenario_name: str = "unnamed",
        seed: Optional[int] = None,
        od_flow_observer: Optional[Callable] = None,
    ) -> SimulationResults:
        """
        Execute the simulation.

        Parameters
        ----------
        trip_requests:
            List of TripRequest objects (generated by ODMatrix.generate_trips).
        scenario_name:
            Label for the results object.
        seed:
            Random seed.  Overrides config value if provided.
        od_flow_observer:
            Optional callback(link_id, agent_id, time_min) called at each
            edge traversal.  Used for calibration against observed counts.

        Returns
        -------
        SimulationResults with all events and station statistics.
        """
        effective_seed = seed if seed is not None else self.config.get(
            "simulation", {}
        ).get("random_seed", 42)
        rng = np.random.default_rng(effective_seed)

        sim_duration = self.config.get("simulation", {}).get(
            "sim_duration_min", 1440.0
        )

        # --- Create SimPy environment ---
        env = simpy.Environment()
        collector = ResultsCollector()

        # --- Initialise station resources ---
        for station in self.stations:
            station.init_resource(env)
            # Reset statistics from previous runs
            station.total_sessions = 0
            station.total_energy_kwh = 0.0
            station.total_wait_time_min = 0.0
            station.total_charge_time_min = 0.0
            station.peak_queue_length = 0

        # --- Convert TripRequests → VehicleAgents ---
        flat_config = _flatten_config(self.config)
        agents = [
            _create_agent(trip, flat_config, rng)
            for trip in trip_requests
        ]
        logger.info(
            "Simulation '%s': %d agents, %d stations",
            scenario_name, len(agents), len(self.stations),
        )

        # --- Schedule all trip processes ---
        for agent in agents:
            env.process(
                vehicle_trip_process(
                    env=env,
                    agent=agent,
                    network=self.network,
                    stations_by_node=self.stations_by_node,
                    config=flat_config,
                    collector=collector,
                    rng=rng,
                )
            )

        # --- Run ---
        env.run(until=sim_duration)

        # --- Collect results ---
        results = collector.to_results(
            stations=self.stations,
            scenario_name=scenario_name,
            sim_duration_min=sim_duration,
        )
        logger.info(
            "Simulation '%s' complete. "
            "Completion=%.1f%%, stranded=%d, "
            "total_charge_events=%d, total_energy=%.0f kWh",
            scenario_name,
            results.completion_rate() * 100,
            sum(1 for r in results.trip_records if r.status == "stranded"),
            len(results.charge_events),
            results.total_energy_dispensed_kwh(),
        )
        return results


# ---------------------------------------------------------------------------
# Agent factory
# ---------------------------------------------------------------------------

def _create_agent(
    trip: TripRequest,
    config: Dict,
    rng: np.random.Generator,
) -> VehicleAgent:
    """
    Create a VehicleAgent from a TripRequest with heterogeneous parameters.

    Parameters are sampled from distributions calibrated to represent
    a realistic BEV fleet on Spanish interurban roads.
    """
    # Fleet mix
    battery_dist = config.get("fleet_battery_distribution", {
        "small": {"capacity_kwh": 45, "fraction": 0.15},
        "medium": {"capacity_kwh": 65, "fraction": 0.40},
        "large": {"capacity_kwh": 77, "fraction": 0.35},
        "xl": {"capacity_kwh": 100, "fraction": 0.10},
    })
    acceptance_map = config.get("fleet_acceptance_kw", {
        "small": 80, "medium": 135, "large": 150, "xl": 250
    })

    types = list(battery_dist.keys())
    fractions = [battery_dist[t]["fraction"] for t in types]
    vtype = rng.choice(types, p=fractions)
    battery_kwh = float(battery_dist[vtype]["capacity_kwh"])
    acceptance_kw = float(acceptance_map.get(vtype, 150))

    # Home charging
    home_pen = config.get("fleet_home_charging_penetration", 0.70)
    home_charging = rng.random() < home_pen
    dest_pen = config.get("fleet_destination_charging_penetration", 0.20)
    dest_charging = rng.random() < dest_pen

    # Behavioral parameters — drawn from plausible distributions
    vot_eur_hr = float(rng.lognormal(
        mean=np.log(config.get("default_value_of_time_eur_per_hour", 28.0)),
        sigma=0.4,
    ))
    vot_eur_hr = float(np.clip(vot_eur_hr, 10.0, 80.0))

    price_sens = float(rng.lognormal(mean=0.0, sigma=0.3))
    price_sens = float(np.clip(price_sens, 0.2, 3.0))

    queue_aversion = float(rng.lognormal(mean=0.0, sigma=0.4))
    queue_aversion = float(np.clip(queue_aversion, 0.1, 4.0))

    risk_tol = float(rng.beta(2, 3))  # mostly risk-averse (mean ~0.4)

    consumption = float(rng.normal(
        loc=config.get("default_consumption_kwh_per_km", 0.20),
        scale=0.02,
    ))
    consumption = float(np.clip(consumption, 0.14, 0.28))

    return VehicleAgent(
        agent_id=trip.trip_id,
        origin=trip.origin,
        destination=trip.destination,
        departure_time_min=trip.departure_time_min,
        battery_capacity_kwh=battery_kwh,
        usable_capacity_kwh=battery_kwh * 0.90,
        consumption_kwh_per_km=consumption,
        max_acceptance_kw=acceptance_kw,
        vehicle_type=vtype,
        home_charging_access=home_charging,
        destination_charging_access=dest_charging,
        value_of_time_eur_per_hour=vot_eur_hr,
        price_sensitivity=price_sens,
        queue_aversion=queue_aversion,
        risk_tolerance=risk_tol,
    )


def _flatten_config(config: Dict) -> Dict:
    """
    Collapse nested YAML config into a flat dict for easy lookup.

    Nested keys like config["behavior"]["min_reserve_soc_fraction"]
    become flat keys like flat["min_reserve_soc_fraction"].
    Top-level keys (simulation, energy_model, etc.) are kept too.
    """
    flat = dict(config)  # keep top-level as-is
    for section_key, section_val in config.items():
        if isinstance(section_val, dict):
            for k, v in section_val.items():
                flat[k] = v
                # Also preserve nested dicts (like battery_distribution)
                if isinstance(v, dict):
                    flat[k] = v
    return flat
