"""
Build visualization/dashboard_data.js from pipeline outputs.

Run:
    .venv/bin/python visualization/build_dashboard_data.py

Produces a single JS file with all datasets needed by
visualization/ev_network_dashboard.html as inlined constants.
"""
from __future__ import annotations

import json
from pathlib import Path

import geopandas as gpd
import pandas as pd
from shapely.geometry import mapping

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "processed"
OUT = ROOT / "output"
TARGET = ROOT / "visualization" / "dashboard_data.js"


def load_provinces() -> dict:
    gdf = gpd.read_file(DATA / "provinces.geojson")
    keep = [c for c in ("nombre", "name", "NAME_2", "cod_prov", "codigo") if c in gdf.columns]
    gdf = gdf[keep + ["geometry"]].copy()
    gdf["geometry"] = gdf.geometry.simplify(tolerance=0.01, preserve_topology=True)
    return json.loads(gdf.to_json())


def load_tent() -> dict:
    gdf = gpd.read_file(DATA / "tent_corridors.geojson")
    # Detect tier column
    tier_col = None
    for c in ("TENT_red_basica", "tent_tier", "tier", "TENT"):
        if c in gdf.columns:
            tier_col = c
            break
    keep = [c for c in ("Carretera", "road", "name") if c in gdf.columns]
    if tier_col:
        keep.append(tier_col)
    gdf = gdf[keep + ["geometry"]].copy()
    if tier_col and tier_col != "tier":
        gdf = gdf.rename(columns={tier_col: "tier"})
    gdf["geometry"] = gdf.geometry.simplify(tolerance=0.005, preserve_topology=True)
    return json.loads(gdf.to_json())


def load_service_areas() -> dict:
    gdf = gpd.read_file(DATA / "service_areas_clean.geojson")
    return json.loads(gdf.to_json())


def load_substations() -> list[dict]:
    df = pd.read_csv(DATA / "grid_consolidated.csv")
    df = df[["substation_name", "latitude", "longitude", "available_capacity_mw",
             "distributor_network", "grid_status", "voltage_kv"]].copy()
    df = df.rename(columns={
        "substation_name": "name",
        "latitude": "lat",
        "longitude": "lon",
        "available_capacity_mw": "mw",
        "distributor_network": "dso",
        "grid_status": "status",
        "voltage_kv": "kv",
    })
    df["mw"] = df["mw"].round(3)
    return df.to_dict(orient="records")


def load_existing_chargers() -> list[dict]:
    df = pd.read_csv(DATA / "interurban_chargers_baseline.csv")
    df = df[["latitude", "longitude", "max_power_kw", "nearest_road"]].copy()
    df = df.rename(columns={
        "latitude": "lat",
        "longitude": "lon",
        "max_power_kw": "kw",
        "nearest_road": "road",
    })
    df["kw"] = df["kw"].fillna(0).round(0).astype(int)
    return df.to_dict(orient="records")


def load_demand_heatmap() -> list[dict]:
    roads = gpd.read_parquet(DATA / "interurban_roads.parquet")[["segment_id", "geometry"]]
    # Project to metric CRS for accurate centroid, then back to WGS84
    centroids = roads.to_crs(25830).geometry.centroid.to_crs(4326)
    roads = roads.assign(lat=centroids.y.values, lon=centroids.x.values).drop(columns=["geometry"])
    demand = pd.read_csv(DATA / "demand_per_segment.csv")
    merged = demand.merge(roads, on="segment_id", how="inner")
    merged = merged[["lat", "lon", "daily_bev_traffic_2027", "n_chargers_needed",
                     "route_segment", "tent_tier"]].copy()
    merged = merged.rename(columns={
        "daily_bev_traffic_2027": "bev",
        "n_chargers_needed": "ch",
        "route_segment": "route",
        "tent_tier": "tier",
    })
    merged["bev"] = merged["bev"].round(0).astype(int)
    return merged.to_dict(orient="records")


def load_csv_points(path: Path) -> list[dict]:
    return pd.read_csv(path).to_dict(orient="records")


def load_kpis() -> dict:
    f1 = pd.read_csv(OUT / "File_1.csv").iloc[0].to_dict()
    dso = pd.read_csv(OUT / "dso_investment_summary.csv").to_dict(orient="records")
    return {"summary": f1, "dso": dso}


def main() -> None:
    payload = {
        "provinces": load_provinces(),
        "tent": load_tent(),
        "dso_areas": load_service_areas(),
        "substations": load_substations(),
        "existing_chargers": load_existing_chargers(),
        "demand": load_demand_heatmap(),
        "proposed": load_csv_points(OUT / "File_2.csv"),
        "friction": load_csv_points(OUT / "File_3.csv"),
        "kpis": load_kpis(),
    }

    js = "// Auto-generated by build_dashboard_data.py. Do not edit.\n"
    for key, value in payload.items():
        js += f"const DATA_{key.upper()} = {json.dumps(value, ensure_ascii=False, separators=(',', ':'))};\n"

    TARGET.write_text(js, encoding="utf-8")
    size_kb = TARGET.stat().st_size / 1024
    print(f"Wrote {TARGET.relative_to(ROOT)}  ({size_kb:.0f} KB)")
    for k, v in payload.items():
        if isinstance(v, list):
            print(f"  {k}: {len(v)} records")
        elif isinstance(v, dict) and "features" in v:
            print(f"  {k}: {len(v['features'])} features")
        else:
            print(f"  {k}: object")


if __name__ == "__main__":
    main()
